
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
Prisma.prismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  passwordHash: 'passwordHash',
  balance: 'balance',
  holdBalance: 'holdBalance',
  role: 'role',
  telegramId: 'telegramId',
  twoFactorSecret: 'twoFactorSecret',
  twoFactorEnabled: 'twoFactorEnabled',
  level: 'level',
  totalRevenue: 'totalRevenue',
  isActive: 'isActive',
  avatar: 'avatar',
  fullName: 'fullName',
  phone: 'phone',
  bankAccount: 'bankAccount',
  bankName: 'bankName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SellerRequestScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  phone: 'phone',
  facebook: 'facebook',
  cccd: 'cccd',
  bankName: 'bankName',
  bankAccount: 'bankAccount',
  telegram: 'telegram',
  status: 'status',
  adminNote: 'adminNote',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  icon: 'icon',
  parentId: 'parentId',
  createdAt: 'createdAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  categoryId: 'categoryId',
  title: 'title',
  slug: 'slug',
  shortDescription: 'shortDescription',
  description: 'description',
  type: 'type',
  price: 'price',
  priceMax: 'priceMax',
  thumbnail: 'thumbnail',
  status: 'status',
  isFeatured: 'isFeatured',
  isSponsored: 'isSponsored',
  viewCount: 'viewCount',
  soldCount: 'soldCount',
  rating: 'rating',
  warrantyDays: 'warrantyDays',
  lastSoldAt: 'lastSoldAt',
  isService: 'isService',
  allowBidding: 'allowBidding',
  deliveryTimeHours: 'deliveryTimeHours',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  price: 'price',
  allowBidding: 'allowBidding',
  description: 'description',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  deliveryTimeHours: 'deliveryTimeHours'
};

exports.Prisma.ProductItemScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  variantId: 'variantId',
  content: 'content',
  isSold: 'isSold',
  soldAt: 'soldAt',
  createdAt: 'createdAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  buyerId: 'buyerId',
  sellerId: 'sellerId',
  productId: 'productId',
  variantId: 'variantId',
  variantName: 'variantName',
  quantity: 'quantity',
  amount: 'amount',
  fee: 'fee',
  status: 'status',
  deliveredContent: 'deliveredContent',
  warrantyExpire: 'warrantyExpire',
  couponCode: 'couponCode',
  discountAmount: 'discountAmount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  buyerConfirmedAt: 'buyerConfirmedAt',
  customPrice: 'customPrice',
  deliveredAt: 'deliveredAt',
  startedAt: 'startedAt',
  negotiatedDeliveryHours: 'negotiatedDeliveryHours',
  pendingExtensionHours: 'pendingExtensionHours'
};

exports.Prisma.DisputeScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  reason: 'reason',
  evidence: 'evidence',
  faultyCount: 'faultyCount',
  status: 'status',
  resolution: 'resolution',
  sellerReply: 'sellerReply',
  adminDecision: 'adminDecision',
  refundAmount: 'refundAmount',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt'
};

exports.Prisma.DisputeMessageScalarFieldEnum = {
  id: 'id',
  disputeId: 'disputeId',
  senderId: 'senderId',
  senderRole: 'senderRole',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  type: 'type',
  status: 'status',
  gatewayRef: 'gatewayRef',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  rating: 'rating',
  comment: 'comment',
  createdAt: 'createdAt',
  sellerReply: 'sellerReply',
  sellerReplyAt: 'sellerReplyAt'
};

exports.Prisma.CouponScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  code: 'code',
  discountType: 'discountType',
  discountValue: 'discountValue',
  usageLimit: 'usageLimit',
  usageCount: 'usageCount',
  expiresAt: 'expiresAt',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.AffiliateLinkScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  code: 'code',
  commissionRate: 'commissionRate',
  totalEarned: 'totalEarned',
  clickCount: 'clickCount',
  createdAt: 'createdAt'
};

exports.Prisma.ChatLogScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  message: 'message',
  aiResponse: 'aiResponse',
  contextSummary: 'contextSummary',
  createdAt: 'createdAt'
};

exports.Prisma.BannerScalarFieldEnum = {
  id: 'id',
  imageUrl: 'imageUrl',
  linkUrl: 'linkUrl',
  title: 'title',
  isActive: 'isActive',
  order: 'order',
  createdAt: 'createdAt'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  message: 'message',
  isActive: 'isActive',
  order: 'order',
  createdAt: 'createdAt'
};

exports.Prisma.SystemConfigScalarFieldEnum = {
  id: 'id',
  maxBoothsPerSeller: 'maxBoothsPerSeller',
  maxItemsPerOrder: 'maxItemsPerOrder',
  commissionRate: 'commissionRate',
  minWithdrawAmount: 'minWithdrawAmount',
  maintenanceMode: 'maintenanceMode',
  updatedAt: 'updatedAt',
  sepayApiKey: 'sepayApiKey',
  sepayMerchantId: 'sepayMerchantId',
  sepayWebhookSecret: 'sepayWebhookSecret',
  bankAccount: 'bankAccount',
  bankName: 'bankName',
  bankOwner: 'bankOwner'
};

exports.Prisma.UserOverrideScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  maxBooths: 'maxBooths',
  maxItemsPerOrder: 'maxItemsPerOrder',
  commissionRate: 'commissionRate',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatRoomScalarFieldEnum = {
  id: 'id',
  isGroup: 'isGroup',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatParticipantScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  userId: 'userId',
  lastRead: 'lastRead',
  joinedAt: 'joinedAt'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  senderId: 'senderId',
  content: 'content',
  createdAt: 'createdAt',
  isSystem: 'isSystem'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  content: 'content',
  type: 'type',
  targetUrl: 'targetUrl',
  isRead: 'isRead',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  SellerRequest: 'SellerRequest',
  Category: 'Category',
  Product: 'Product',
  ProductVariant: 'ProductVariant',
  ProductItem: 'ProductItem',
  Order: 'Order',
  Dispute: 'Dispute',
  DisputeMessage: 'DisputeMessage',
  Transaction: 'Transaction',
  Review: 'Review',
  Coupon: 'Coupon',
  AffiliateLink: 'AffiliateLink',
  ChatLog: 'ChatLog',
  Banner: 'Banner',
  Announcement: 'Announcement',
  SystemConfig: 'SystemConfig',
  UserOverride: 'UserOverride',
  ChatRoom: 'ChatRoom',
  ChatParticipant: 'ChatParticipant',
  ChatMessage: 'ChatMessage',
  Notification: 'Notification'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
